/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.dikshatech.portal.dto;

import java.io.Serializable;

import com.dikshatech.portal.forms.PortalForm;

public class EmployeeType extends PortalForm implements Serializable
{
	/** 
	 * This attribute maps to the column ID in the EMPLOYEE_TYPE table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column EMPLOYEE_TYPE in the EMPLOYEE_TYPE table.
	 */
	protected String employeeType;

	/**
	 * Method 'EmployeeType'
	 * 
	 */
	public EmployeeType()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getEmployeeType'
	 * 
	 * @return String
	 */
	public String getEmployeeType()
	{
		return employeeType;
	}

	/**
	 * Method 'setEmployeeType'
	 * 
	 * @param employeeType
	 */
	public void setEmployeeType(String employeeType)
	{
		this.employeeType = employeeType;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof EmployeeType)) {
			return false;
		}
		
		final EmployeeType _cast = (EmployeeType) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (employeeType == null ? _cast.employeeType != employeeType : !employeeType.equals( _cast.employeeType )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (employeeType != null) {
			_hashCode = 29 * _hashCode + employeeType.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return EmployeeTypePk
	 */
	public EmployeeTypePk createPk()
	{
		return new EmployeeTypePk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.dikshatech.portal.dto.EmployeeType: " );
		ret.append( "id=" + id );
		ret.append( ", employeeType=" + employeeType );
		return ret.toString();
	}

}
