/*
 * This source file was generated by FireStorm/DAO.
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package com.dikshatech.portal.dto;

import java.io.Serializable;

public class ExitQuestions implements Serializable {

	/**
	 * This attribute maps to the column ID in the EXIT_QUESTIONS table.
	 */
	protected int		id;
	/**
	 * This attribute maps to the column TYPE in the EXIT_QUESTIONS table.
	 */
	protected String	type;
	/**
	 * This attribute maps to the column QUESTION in the EXIT_QUESTIONS table.
	 */
	protected String	question;
	private String		answer;
	private Object[]	questions;

	/**
	 * Method 'ExitQuestions'
	 */
	public ExitQuestions() {}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId() {
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Method 'getType'
	 * 
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/**
	 * Method 'setType'
	 * 
	 * @param type
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Method 'getQuestion'
	 * 
	 * @return String
	 */
	public String getQuestion() {
		return question;
	}

	/**
	 * Method 'setQuestion'
	 * 
	 * @param question
	 */
	public void setQuestion(String question) {
		this.question = question;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other) {
		if (_other == null){
			return false;
		}
		if (_other == this){
			return true;
		}
		if (!(_other instanceof ExitQuestions)){
			return false;
		}
		final ExitQuestions _cast = (ExitQuestions) _other;
		if (id != _cast.id){
			return false;
		}
		if (type == null ? _cast.type != type : !type.equals(_cast.type)){
			return false;
		}
		if (question == null ? _cast.question != question : !question.equals(_cast.question)){
			return false;
		}
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode() {
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (type != null){
			_hashCode = 29 * _hashCode + type.hashCode();
		}
		if (question != null){
			_hashCode = 29 * _hashCode + question.hashCode();
		}
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ExitQuestionsPk
	 */
	public ExitQuestionsPk createPk() {
		return new ExitQuestionsPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer ret = new StringBuffer();
		ret.append("com.dikshatech.portal.dto.ExitQuestions: ");
		ret.append("id=" + id);
		ret.append(", type=" + type);
		ret.append(", question=" + question);
		ret.append(", answer=" + answer);
		return ret.toString();
	}

	public void setQuestions(Object[] questions) {
		this.questions = questions;
	}

	public Object[] getQuestions() {
		return questions;
	}

	public void setAnswer(String answer) {
		this.answer = (answer == null) ? "" : answer;
	}

	public String getAnswer() {
		return answer;
	}

	public ExitQuestions(int id, String type, String question, String answer) {
		this.id = id;
		this.type = type;
		this.question = question;
		setAnswer(answer);
	}
}
