/*
 * This source file was generated by FireStorm/DAO.
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package com.dikshatech.portal.dto;

import java.io.Serializable;
import java.util.Date;

public class InsurancePolicyReq implements Serializable {

	/**
	 * This attribute maps to the column ID in the INSURANCE_POLICY_REQ table.
	 */
	protected int		id;
	/**
	 * This attribute maps to the column ESR_MAP_ID in the INSURANCE_POLICY_REQ table.
	 */
	protected int		esrMapId;
	/**
	 * This attribute represents whether the primitive attribute esrMapId is null.
	 */
	protected boolean	esrMapIdNull		= true;
	/**
	 * This attribute maps to the column STATUS in the INSURANCE_POLICY_REQ table.
	 */
	protected String	status;
	/**
	 * This attribute maps to the column REQUETER_ID in the INSURANCE_POLICY_REQ table.
	 */
	protected int		requeterId;
	/**
	 * This attribute represents whether the primitive attribute requeterId is null.
	 */
	protected boolean	requeterIdNull		= true;
	/**
	 * This attribute maps to the column POLICY_NUMBER in the INSURANCE_POLICY_REQ table.
	 */
	protected String	policyNumber;
	/**
	 * This attribute maps to the column POLICY_TYPE in the INSURANCE_POLICY_REQ table.
	 */
	protected String	policyType;
	/**
	 * This attribute maps to the column COVERAGE in the INSURANCE_POLICY_REQ table.
	 */
	protected int		coverage;
	/**
	 * This attribute represents whether the primitive attribute coverage is null.
	 */
	protected boolean	coverageNull		= true;
	/**
	 * This attribute maps to the column COVERAGE_FROM in the INSURANCE_POLICY_REQ table.
	 */
	protected Date		coverageFrom;
	/**
	 * This attribute maps to the column COVERAGE_UPTO in the INSURANCE_POLICY_REQ table.
	 */
	protected Date		coverageUpto;
	/**
	 * This attribute maps to the column DELIVERY_ADDRESS in the INSURANCE_POLICY_REQ table.
	 */
	protected String	deliveryAddress;
	/**
	 * This attribute maps to the column BASIC_PREMIUM in the INSURANCE_POLICY_REQ table.
	 */
	protected int		basicPremium;
	/**
	 * This attribute represents whether the primitive attribute basicPremium is null.
	 */
	protected boolean	basicPremiumNull	= true;
	/**
	 * This attribute maps to the column SERVICE_TAX in the INSURANCE_POLICY_REQ table.
	 */
	protected int		serviceTax;
	/**
	 * This attribute represents whether the primitive attribute serviceTax is null.
	 */
	protected boolean	serviceTaxNull		= true;
	/**
	 * This attribute maps to the column REQUESTED_ON in the INSURANCE_POLICY_REQ table.
	 */
	protected Date		requestedOn;
	/**
	 * This attribute maps to the column DATE_OF_COMPLETION in the INSURANCE_POLICY_REQ table.
	 */
	protected Date		dateOfCompletion;
	/**
	 * This attribute maps to the column TOTAL_PREMIUM in the INSURANCE_POLICY_REQ table.
	 */
	protected int		totalPremium;
	/**
	 * This attribute represents whether the primitive attribute totalPremium is null.
	 */
	protected boolean	totalPremiumNull	= true;
	/**
	 * This attribute maps to the column INSURANCE_COMPANY_NAME in the INSURANCE_POLICY_REQ table.
	 */
	protected String	insuranceCompanyName;
	/**
	 * Method 'InsurancePolicyReq'
	 */
	protected String	comments;
	private String		name;

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public InsurancePolicyReq() {}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId() {
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Method 'getEsrMapId'
	 * 
	 * @return int
	 */
	public int getEsrMapId() {
		return esrMapId;
	}

	/**
	 * Method 'setEsrMapId'
	 * 
	 * @param esrMapId
	 */
	public void setEsrMapId(int esrMapId) {
		this.esrMapId = esrMapId;
		this.esrMapIdNull = false;
	}

	/**
	 * Method 'setEsrMapIdNull'
	 * 
	 * @param value
	 */
	public void setEsrMapIdNull(boolean value) {
		this.esrMapIdNull = value;
	}

	/**
	 * Method 'isEsrMapIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isEsrMapIdNull() {
		return esrMapIdNull;
	}

	/**
	 * Method 'getStatus'
	 * 
	 * @return String
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * Method 'setStatus'
	 * 
	 * @param status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Method 'getRequeterId'
	 * 
	 * @return int
	 */
	public int getRequeterId() {
		return requeterId;
	}

	/**
	 * Method 'setRequeterId'
	 * 
	 * @param requeterId
	 */
	public void setRequeterId(int requeterId) {
		this.requeterId = requeterId;
		this.requeterIdNull = false;
	}

	/**
	 * Method 'setRequeterIdNull'
	 * 
	 * @param value
	 */
	public void setRequeterIdNull(boolean value) {
		this.requeterIdNull = value;
	}

	/**
	 * Method 'isRequeterIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isRequeterIdNull() {
		return requeterIdNull;
	}

	/**
	 * Method 'getPolicyNumber'
	 * 
	 * @return String
	 */
	public String getPolicyNumber() {
		return policyNumber;
	}

	/**
	 * Method 'setPolicyNumber'
	 * 
	 * @param policyNumber
	 */
	public void setPolicyNumber(String policyNumber) {
		this.policyNumber = policyNumber;
	}

	/**
	 * Method 'getPolicyType'
	 * 
	 * @return String
	 */
	public String getPolicyType() {
		return policyType;
	}

	/**
	 * Method 'setPolicyType'
	 * 
	 * @param policyType
	 */
	public void setPolicyType(String policyType) {
		this.policyType = policyType;
	}

	/**
	 * Method 'getCoverage'
	 * 
	 * @return int
	 */
	public int getCoverage() {
		return coverage;
	}

	/**
	 * Method 'setCoverage'
	 * 
	 * @param coverage
	 */
	public void setCoverage(int coverage) {
		this.coverage = coverage;
		this.coverageNull = false;
	}

	/**
	 * Method 'setCoverageNull'
	 * 
	 * @param value
	 */
	public void setCoverageNull(boolean value) {
		this.coverageNull = value;
	}

	/**
	 * Method 'isCoverageNull'
	 * 
	 * @return boolean
	 */
	public boolean isCoverageNull() {
		return coverageNull;
	}

	/**
	 * Method 'getCoverageFrom'
	 * 
	 * @return Date
	 */
	public Date getCoverageFrom() {
		return coverageFrom;
	}

	/**
	 * Method 'setCoverageFrom'
	 * 
	 * @param coverageFrom
	 */
	public void setCoverageFrom(Date coverageFrom) {
		this.coverageFrom = coverageFrom;
	}

	/**
	 * Method 'getCoverageUpto'
	 * 
	 * @return Date
	 */
	public Date getCoverageUpto() {
		return coverageUpto;
	}

	/**
	 * Method 'setCoverageUpto'
	 * 
	 * @param coverageUpto
	 */
	public void setCoverageUpto(Date coverageUpto) {
		this.coverageUpto = coverageUpto;
	}

	/**
	 * Method 'getDeliveryAddress'
	 * 
	 * @return String
	 */
	public String getDeliveryAddress() {
		return deliveryAddress;
	}

	/**
	 * Method 'setDeliveryAddress'
	 * 
	 * @param deliveryAddress
	 */
	public void setDeliveryAddress(String deliveryAddress) {
		this.deliveryAddress = deliveryAddress;
	}

	/**
	 * Method 'getBasicPremium'
	 * 
	 * @return int
	 */
	public int getBasicPremium() {
		return basicPremium;
	}

	/**
	 * Method 'setBasicPremium'
	 * 
	 * @param basicPremium
	 */
	public void setBasicPremium(int basicPremium) {
		this.basicPremium = basicPremium;
		this.basicPremiumNull = false;
	}

	/**
	 * Method 'setBasicPremiumNull'
	 * 
	 * @param value
	 */
	public void setBasicPremiumNull(boolean value) {
		this.basicPremiumNull = value;
	}

	/**
	 * Method 'isBasicPremiumNull'
	 * 
	 * @return boolean
	 */
	public boolean isBasicPremiumNull() {
		return basicPremiumNull;
	}

	/**
	 * Method 'getServiceTax'
	 * 
	 * @return int
	 */
	public int getServiceTax() {
		return serviceTax;
	}

	/**
	 * Method 'setServiceTax'
	 * 
	 * @param serviceTax
	 */
	public void setServiceTax(int serviceTax) {
		this.serviceTax = serviceTax;
		this.serviceTaxNull = false;
	}

	/**
	 * Method 'setServiceTaxNull'
	 * 
	 * @param value
	 */
	public void setServiceTaxNull(boolean value) {
		this.serviceTaxNull = value;
	}

	/**
	 * Method 'isServiceTaxNull'
	 * 
	 * @return boolean
	 */
	public boolean isServiceTaxNull() {
		return serviceTaxNull;
	}

	/**
	 * Method 'getRequestedOn'
	 * 
	 * @return Date
	 */
	public Date getRequestedOn() {
		return requestedOn;
	}

	/**
	 * Method 'setRequestedOn'
	 * 
	 * @param requestedOn
	 */
	public void setRequestedOn(Date requestedOn) {
		this.requestedOn = requestedOn;
	}

	/**
	 * Method 'getDateOfCompletion'
	 * 
	 * @return Date
	 */
	public Date getDateOfCompletion() {
		return dateOfCompletion;
	}

	/**
	 * Method 'setDateOfCompletion'
	 * 
	 * @param dateOfCompletion
	 */
	public void setDateOfCompletion(Date dateOfCompletion) {
		this.dateOfCompletion = dateOfCompletion;
	}

	/**
	 * Method 'getTotalPremium'
	 * 
	 * @return int
	 */
	public int getTotalPremium() {
		return totalPremium;
	}

	/**
	 * Method 'setTotalPremium'
	 * 
	 * @param totalPremium
	 */
	public void setTotalPremium(int totalPremium) {
		this.totalPremium = totalPremium;
		this.totalPremiumNull = false;
	}

	/**
	 * Method 'setTotalPremiumNull'
	 * 
	 * @param value
	 */
	public void setTotalPremiumNull(boolean value) {
		this.totalPremiumNull = value;
	}

	/**
	 * Method 'isTotalPremiumNull'
	 * 
	 * @return boolean
	 */
	public boolean isTotalPremiumNull() {
		return totalPremiumNull;
	}

	/**
	 * Method 'getInsuranceCompanyName'
	 * 
	 * @return String
	 */
	public String getInsuranceCompanyName() {
		return insuranceCompanyName;
	}

	/**
	 * Method 'setInsuranceCompanyName'
	 * 
	 * @param insuranceCompanyName
	 */
	public void setInsuranceCompanyName(String insuranceCompanyName) {
		this.insuranceCompanyName = insuranceCompanyName;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other) {
		if (_other == null){ return false; }
		if (_other == this){ return true; }
		if (!(_other instanceof InsurancePolicyReq)){ return false; }
		final InsurancePolicyReq _cast = (InsurancePolicyReq) _other;
		if (id != _cast.id){ return false; }
		if (esrMapId != _cast.esrMapId){ return false; }
		if (esrMapIdNull != _cast.esrMapIdNull){ return false; }
		if (status == null ? _cast.status != status : !status.equals(_cast.status)){ return false; }
		if (requeterId != _cast.requeterId){ return false; }
		if (requeterIdNull != _cast.requeterIdNull){ return false; }
		if (policyNumber == null ? _cast.policyNumber != policyNumber : !policyNumber.equals(_cast.policyNumber)){ return false; }
		if (policyType == null ? _cast.policyType != policyType : !policyType.equals(_cast.policyType)){ return false; }
		if (coverage != _cast.coverage){ return false; }
		if (coverageNull != _cast.coverageNull){ return false; }
		if (coverageFrom == null ? _cast.coverageFrom != coverageFrom : !coverageFrom.equals(_cast.coverageFrom)){ return false; }
		if (coverageUpto == null ? _cast.coverageUpto != coverageUpto : !coverageUpto.equals(_cast.coverageUpto)){ return false; }
		if (deliveryAddress == null ? _cast.deliveryAddress != deliveryAddress : !deliveryAddress.equals(_cast.deliveryAddress)){ return false; }
		if (basicPremium != _cast.basicPremium){ return false; }
		if (basicPremiumNull != _cast.basicPremiumNull){ return false; }
		if (serviceTax != _cast.serviceTax){ return false; }
		if (serviceTaxNull != _cast.serviceTaxNull){ return false; }
		if (requestedOn == null ? _cast.requestedOn != requestedOn : !requestedOn.equals(_cast.requestedOn)){ return false; }
		if (dateOfCompletion == null ? _cast.dateOfCompletion != dateOfCompletion : !dateOfCompletion.equals(_cast.dateOfCompletion)){ return false; }
		if (totalPremium != _cast.totalPremium){ return false; }
		if (totalPremiumNull != _cast.totalPremiumNull){ return false; }
		if (insuranceCompanyName == null ? _cast.insuranceCompanyName != insuranceCompanyName : !insuranceCompanyName.equals(_cast.insuranceCompanyName)){ return false; }
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode() {
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + esrMapId;
		_hashCode = 29 * _hashCode + (esrMapIdNull ? 1 : 0);
		if (status != null){
			_hashCode = 29 * _hashCode + status.hashCode();
		}
		_hashCode = 29 * _hashCode + requeterId;
		_hashCode = 29 * _hashCode + (requeterIdNull ? 1 : 0);
		if (policyNumber != null){
			_hashCode = 29 * _hashCode + policyNumber.hashCode();
		}
		if (policyType != null){
			_hashCode = 29 * _hashCode + policyType.hashCode();
		}
		_hashCode = 29 * _hashCode + coverage;
		_hashCode = 29 * _hashCode + (coverageNull ? 1 : 0);
		if (coverageFrom != null){
			_hashCode = 29 * _hashCode + coverageFrom.hashCode();
		}
		if (coverageUpto != null){
			_hashCode = 29 * _hashCode + coverageUpto.hashCode();
		}
		if (deliveryAddress != null){
			_hashCode = 29 * _hashCode + deliveryAddress.hashCode();
		}
		_hashCode = 29 * _hashCode + basicPremium;
		_hashCode = 29 * _hashCode + (basicPremiumNull ? 1 : 0);
		_hashCode = 29 * _hashCode + serviceTax;
		_hashCode = 29 * _hashCode + (serviceTaxNull ? 1 : 0);
		if (requestedOn != null){
			_hashCode = 29 * _hashCode + requestedOn.hashCode();
		}
		if (dateOfCompletion != null){
			_hashCode = 29 * _hashCode + dateOfCompletion.hashCode();
		}
		_hashCode = 29 * _hashCode + totalPremium;
		_hashCode = 29 * _hashCode + (totalPremiumNull ? 1 : 0);
		if (insuranceCompanyName != null){
			_hashCode = 29 * _hashCode + insuranceCompanyName.hashCode();
		}
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return InsurancePolicyReqPk
	 */
	public InsurancePolicyReqPk createPk() {
		return new InsurancePolicyReqPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer ret = new StringBuffer();
		ret.append("com.dikshatech.portal.dto.InsurancePolicyReq: ");
		ret.append("id=" + id);
		ret.append(", esrMapId=" + esrMapId);
		ret.append(", status=" + status);
		ret.append(", requeterId=" + requeterId);
		ret.append(", policyNumber=" + policyNumber);
		ret.append(", policyType=" + policyType);
		ret.append(", coverage=" + coverage);
		ret.append(", coverageFrom=" + coverageFrom);
		ret.append(", coverageUpto=" + coverageUpto);
		ret.append(", deliveryAddress=" + deliveryAddress);
		ret.append(", basicPremium=" + basicPremium);
		ret.append(", serviceTax=" + serviceTax);
		ret.append(", requestedOn=" + requestedOn);
		ret.append(", dateOfCompletion=" + dateOfCompletion);
		ret.append(", totalPremium=" + totalPremium);
		ret.append(", insuranceCompanyName=" + insuranceCompanyName);
		return ret.toString();
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
