/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.dikshatech.portal.dto;

import java.io.Serializable;

import com.dikshatech.common.utils.UserNameBean;
import com.dikshatech.portal.forms.PortalForm;

public class Levels extends PortalForm implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 7421592558009954691L;

	/** 
	 * This attribute maps to the column ID in the LEVELS table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column LABEL in the LEVELS table.
	 */
	protected String label;

	/** 
	 * This attribute maps to the column DESIGNATION in the LEVELS table.
	 */
	protected String designation;

	/** 
	 * This attribute maps to the column DIVISION_ID in the LEVELS table.
	 */
	protected int divisionId;
	
	/** 
	 * This attribute represents whether the primitive attribute divisionId is null.
	 */
	protected boolean divisionIdNull = true;
	
	/** 
	 * This attribute maps to the column DIVISION_NAME in the DIVISON table.
	 */
	protected String divisionName;

	/** 
	 * This attribute represents whether the primitive attribute divisionId is null.
	 */
	protected boolean divisionNameNull = true;
	
	protected int sequence;
	
	protected String component;
	
	private int escalationId;
	
	private int dueDays;
	
	private UserNameBean[] UserNameArr;

	public UserNameBean[] getUserNameArr() {
		return UserNameArr;
	}

	public void setUserNameArr(UserNameBean[] userNameArr) {
		UserNameArr = userNameArr;
	}

	public int getEscalationId() {
		return escalationId;
	}

	public void setEscalationId(int escalationId) {
		this.escalationId = escalationId;
	}

	public int getDueDays() {
		return dueDays;
	}

	public void setDueDays(int dueDays) {
		this.dueDays = dueDays;
	}

	/**
	 * Method 'Levels'
	 * 
	 */
	public Levels()
	{
	}

	public int getSequence()
	{
		return sequence;
	}

	public String getComponent()
	{
		return component;
	}

	public void setSequence(int sequence)
	{
		this.sequence = sequence;
	}

	public void setComponent(String component)
	{
		this.component = component;
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getLabel'
	 * 
	 * @return String
	 */
	public String getLabel()
	{
		return label;
	}

	/**
	 * Method 'setLabel'
	 * 
	 * @param label
	 */
	public void setLabel(String label)
	{
		this.label = label;
	}

	/**
	 * Method 'getDesignation'
	 * 
	 * @return String
	 */
	public String getDesignation()
	{
		return designation;
	}

	/**
	 * Method 'setDesignation'
	 * 
	 * @param designation
	 */
	public void setDesignation(String designation)
	{
		this.designation = designation;
	}

	/**
	 * Method 'getDivisionId'
	 * 
	 * @return int
	 */
	public int getDivisionId()
	{
		return divisionId;
	}

	/**
	 * Method 'setDivisionId'
	 * 
	 * @param divisionId
	 */
	public void setDivisionId(int divisionId)
	{
		this.divisionId = divisionId;
		this.divisionIdNull = false;
	}

	/**
	 * Method 'setDivisionIdNull'
	 * 
	 * @param value
	 */
	public void setDivisionIdNull(boolean value)
	{
		this.divisionIdNull = value;
	}

	/**
	 * Method 'isDivisionIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isDivisionIdNull()
	{
		return divisionIdNull;
	}

	public String getDivisionName()
	{
		return divisionName;
	}

	public boolean isDivisionNameNull()
	{
		return divisionNameNull;
	}

	public void setDivisionName(String divisionName)
	{
		this.divisionName = divisionName;
		this.divisionNameNull = false;
	}

	public void setDivisionNameNull(boolean divisionNameNull)
	{
		this.divisionNameNull = divisionNameNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Levels)) {
			return false;
		}
		
		final Levels _cast = (Levels) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (label == null ? _cast.label != label : !label.equals( _cast.label )) {
			return false;
		}
		
		if (designation == null ? _cast.designation != designation : !designation.equals( _cast.designation )) {
			return false;
		}
		
		if (divisionId != _cast.divisionId) {
			return false;
		}
		
		if (divisionIdNull != _cast.divisionIdNull) {
			return false;
		}
		
		if (divisionName == null ? _cast.divisionName != divisionName : !divisionName.equals( _cast.divisionName )) {
			return false;
		}
		
		if (divisionNameNull != _cast.divisionNameNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (label != null) {
			_hashCode = 29 * _hashCode + label.hashCode();
		}
		
		if (designation != null) {
			_hashCode = 29 * _hashCode + designation.hashCode();
		}
		
		_hashCode = 29 * _hashCode + divisionId;
		_hashCode = 29 * _hashCode + (divisionIdNull ? 1 : 0);
		
		if (divisionName != null) {
			_hashCode = 29 * _hashCode + divisionName.hashCode();
		}
		_hashCode = 29 * _hashCode + (divisionNameNull ? 1 : 0);
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return LevelsPk
	 */
	public LevelsPk createPk()
	{
		return new LevelsPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.dikshatech.portal.dto.Levels: " );
		ret.append( "id=" + id );
		ret.append( ", label=" + label );
		ret.append( ", designation=" + designation );
		ret.append( ", divisionId=" + divisionId );
		ret.append( ", divisionName=" + divisionName );
		
		return ret.toString();
	}

}
