/*
 * This source file was generated by FireStorm/DAO.
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package com.dikshatech.portal.dto;

import java.io.Serializable;
import java.util.Date;
import com.dikshatech.portal.forms.PortalForm;

public class PassportInfo extends PortalForm implements Serializable {

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 3985337637335525392L;
	/**
	 * This attribute maps to the column ID in the PASSPORT_INFO table.
	 */
	protected int				id;
	/**
	 * This attribute maps to the column GIVENNAME in the PASSPORT_INFO table.
	 */
	protected String			givenname;
	/**
	 * This attribute maps to the column SURNAME in the PASSPORT_INFO table.
	 */
	protected String			surname;
	/**
	 * This attribute maps to the column PASSPORT_NO in the PASSPORT_INFO table.
	 */
	protected String			passportNo;
	/**
	 * This attribute maps to the column DATE_OF_ISSUE in the PASSPORT_INFO table.
	 */
	protected Date				dateOfIssue;
	/**
	 * This attribute maps to the column DATE_OF_EXPIRE in the PASSPORT_INFO table.
	 */
	protected Date				dateOfExpire;
	/**
	 * This attribute maps to the column PLACE_OF_ISSUE in the PASSPORT_INFO table.
	 */
	protected String			placeOfIssue;
	/**
	 * This attribute maps to the column PLACE_OF_BIRTH in the PASSPORT_INFO table.
	 */
	protected String			placeOfBirth;
	protected String			files;
	protected Documents			documentArr[];
	private Object				visaInfo[];

	/**
	 * This attribute maps to the column ID in the PASSPORT_INFO table.
	 */
	protected int				modifiedBy;
	/**
	 * Method 'PassportInfo'
	 */
	public PassportInfo() {}

	public int getModifiedBy() {
		return modifiedBy;
	}

	public void setModifiedBy(int modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId() {
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Method 'getGivenname'
	 * 
	 * @return String
	 */
	public String getGivenname() {
		return givenname;
	}

	/**
	 * Method 'setGivenname'
	 * 
	 * @param givenname
	 */
	public void setGivenname(String givenname) {
		this.givenname = givenname;
	}

	/**
	 * Method 'getSurname'
	 * 
	 * @return String
	 */
	public String getSurname() {
		return surname;
	}

	/**
	 * Method 'setSurname'
	 * 
	 * @param surname
	 */
	public void setSurname(String surname) {
		this.surname = surname;
	}

	/**
	 * Method 'getPassportNo'
	 * 
	 * @return String
	 */
	public String getPassportNo() {
		return passportNo;
	}

	/**
	 * Method 'setPassportNo'
	 * 
	 * @param passportNo
	 */
	public void setPassportNo(String passportNo) {
		this.passportNo = passportNo;
	}

	/**
	 * Method 'getDateOfIssue'
	 * 
	 * @return Date
	 */
	public Date getDateOfIssue() {
		return dateOfIssue;
	}

	/**
	 * Method 'setDateOfIssue'
	 * 
	 * @param dateOfIssue
	 */
	public void setDateOfIssue(Date dateOfIssue) {
		this.dateOfIssue = dateOfIssue;
	}

	/**
	 * Method 'getDateOfExpire'
	 * 
	 * @return Date
	 */
	public Date getDateOfExpire() {
		return dateOfExpire;
	}

	/**
	 * Method 'setDateOfExpire'
	 * 
	 * @param dateOfExpire
	 */
	public void setDateOfExpire(Date dateOfExpire) {
		this.dateOfExpire = dateOfExpire;
	}

	/**
	 * Method 'getPlaceOfIssue'
	 * 
	 * @return String
	 */
	public String getPlaceOfIssue() {
		return placeOfIssue;
	}

	/**
	 * Method 'setPlaceOfIssue'
	 * 
	 * @param placeOfIssue
	 */
	public void setPlaceOfIssue(String placeOfIssue) {
		this.placeOfIssue = placeOfIssue;
	}

	/**
	 * Method 'getPlaceOfBirth'
	 * 
	 * @return String
	 */
	public String getPlaceOfBirth() {
		return placeOfBirth;
	}

	/**
	 * Method 'setPlaceOfBirth'
	 * 
	 * @param placeOfBirth
	 */
	public void setPlaceOfBirth(String placeOfBirth) {
		this.placeOfBirth = placeOfBirth;
	}

	public Documents[] getDocumentArr() {
		return documentArr;
	}

	public void setDocumentArr(Documents[] documentArr) {
		this.documentArr = documentArr;
	}

	public String getFiles() {
		return files;
	}

	public void setFiles(String files) {
		this.files = files;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other) {
		if (_other == null){
			return false;
		}
		if (_other == this){
			return true;
		}
		if (!(_other instanceof PassportInfo)){
			return false;
		}
		final PassportInfo _cast = (PassportInfo) _other;
		if (id != _cast.id){
			return false;
		}
		if (givenname == null ? _cast.givenname != givenname : !givenname.equals(_cast.givenname)){
			return false;
		}
		if (surname == null ? _cast.surname != surname : !surname.equals(_cast.surname)){
			return false;
		}
		if (passportNo == null ? _cast.passportNo != passportNo : !passportNo.equals(_cast.passportNo)){
			return false;
		}
		if (dateOfIssue == null ? _cast.dateOfIssue != dateOfIssue : !dateOfIssue.equals(_cast.dateOfIssue)){
			return false;
		}
		if (dateOfExpire == null ? _cast.dateOfExpire != dateOfExpire : !dateOfExpire.equals(_cast.dateOfExpire)){
			return false;
		}
		if (placeOfIssue == null ? _cast.placeOfIssue != placeOfIssue : !placeOfIssue.equals(_cast.placeOfIssue)){
			return false;
		}
		if (placeOfBirth == null ? _cast.placeOfBirth != placeOfBirth : !placeOfBirth.equals(_cast.placeOfBirth)){
			return false;
		}
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode() {
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (givenname != null){
			_hashCode = 29 * _hashCode + givenname.hashCode();
		}
		if (surname != null){
			_hashCode = 29 * _hashCode + surname.hashCode();
		}
		if (passportNo != null){
			_hashCode = 29 * _hashCode + passportNo.hashCode();
		}
		if (dateOfIssue != null){
			_hashCode = 29 * _hashCode + dateOfIssue.hashCode();
		}
		if (dateOfExpire != null){
			_hashCode = 29 * _hashCode + dateOfExpire.hashCode();
		}
		if (placeOfIssue != null){
			_hashCode = 29 * _hashCode + placeOfIssue.hashCode();
		}
		if (placeOfBirth != null){
			_hashCode = 29 * _hashCode + placeOfBirth.hashCode();
		}
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PassportInfoPk
	 */
	public PassportInfoPk createPk() {
		return new PassportInfoPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer ret = new StringBuffer();
		ret.append("com.dikshatech.portal.dto.PassportInfo: ");
		ret.append("id=" + id);
		ret.append(", givenname=" + givenname);
		ret.append(", surname=" + surname);
		ret.append(", passportNo=" + passportNo);
		ret.append(", dateOfIssue=" + dateOfIssue);
		ret.append(", dateOfExpire=" + dateOfExpire);
		ret.append(", placeOfIssue=" + placeOfIssue);
		ret.append(", placeOfBirth=" + placeOfBirth);
		return ret.toString();
	}

	public Object[] getVisaInfo() {
		return visaInfo;
	}

	public void setVisaInfo(Object visaInfo[]) {
		this.visaInfo = visaInfo;
	}
}
