package com.dikshatech.portal.file.system;

public enum DocumentTypes {
	EDUCATIONAL, EXPERIENCE, OFFER_LETTER, FINANCIAL, INDUCTION, POLICY, PASSPORT, LEAVE, PAYSLIP, REIMBURSEMENT, ITSUPPORT, TRAVEL, NEWS, LEAVES_XLS, REFERFRIEND, RESUMEMANAGEMENT, REIMBURSEMENTLIST , 
 INSURANCE_XLS, FBP_XLS, BENEFIT_XLS, CANDIDATE_CHKLST, TIMESHEET_CONSULTANTS, TDS_XLS, APPRAISAL_PROJECTS, BILLABLE_DAYS,
 PROPOSED_RESOURCE,bgc_seperation,bgc_experience,SAL_XLS, NETSALARY_XLS, GROSSSALARY_XLS, PER_XLS;
}
