/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.dikshatech.portal.jdbc;

import com.dikshatech.portal.dao.*;
import com.dikshatech.portal.factory.*;
import java.util.Date;
import com.dikshatech.portal.dto.*;
import com.dikshatech.portal.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import org.apache.log4j.Logger;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class EmpSerReqHistoryDaoImpl extends AbstractDAO implements EmpSerReqHistoryDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	protected static final Logger logger = Logger.getLogger( EmpSerReqHistoryDaoImpl.class );

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID, ESR_MAP_ID, ACTION_ON, ASSIGNED_TO, ASSIGNED_BY, COMMENTS FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID, ESR_MAP_ID, ACTION_ON, ASSIGNED_TO, ASSIGNED_BY, COMMENTS ) VALUES ( ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID = ?, ESR_MAP_ID = ?, ACTION_ON = ?, ASSIGNED_TO = ?, ASSIGNED_BY = ?, COMMENTS = ? WHERE ID = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID = ?";

	/** 
	 * Index of column ID
	 */
	protected static final int COLUMN_ID = 1;

	/** 
	 * Index of column ESR_MAP_ID
	 */
	protected static final int COLUMN_ESR_MAP_ID = 2;

	/** 
	 * Index of column ACTION_ON
	 */
	protected static final int COLUMN_ACTION_ON = 3;

	/** 
	 * Index of column ASSIGNED_TO
	 */
	protected static final int COLUMN_ASSIGNED_TO = 4;

	/** 
	 * Index of column ASSIGNED_BY
	 */
	protected static final int COLUMN_ASSIGNED_BY = 5;

	/** 
	 * Index of column COMMENTS
	 */
	protected static final int COLUMN_COMMENTS = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column ID
	 */
	protected static final int PK_COLUMN_ID = 1;

	/** 
	 * Inserts a new row in the EMP_SER_REQ_HISTORY table.
	 */
	public EmpSerReqHistoryPk insert(EmpSerReqHistory dto) throws EmpSerReqHistoryDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getId() );
			stmt.setInt( index++, dto.getEsrMapId() );
			stmt.setTimestamp(index++, dto.getActionOn()==null ? null : new java.sql.Timestamp( dto.getActionOn().getTime() ) );
			stmt.setInt( index++, dto.getAssignedTo() );
			stmt.setInt( index++, dto.getAssignedBy() );
			stmt.setString( index++, dto.getComments() );
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL_INSERT + " with DTO: " + dto);
			}
		
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setId( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new EmpSerReqHistoryDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the EMP_SER_REQ_HISTORY table.
	 */
	public void update(EmpSerReqHistoryPk pk, EmpSerReqHistory dto) throws EmpSerReqHistoryDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL_UPDATE + " with DTO: " + dto);
			}
		
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getId() );
			stmt.setInt( index++, dto.getEsrMapId() );
			stmt.setTimestamp(index++, dto.getActionOn()==null ? null : new java.sql.Timestamp( dto.getActionOn().getTime() ) );
			stmt.setInt( index++, dto.getAssignedTo() );
			stmt.setInt( index++, dto.getAssignedBy() );
			stmt.setString( index++, dto.getComments() );
			stmt.setInt( 7, pk.getId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new EmpSerReqHistoryDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the EMP_SER_REQ_HISTORY table.
	 */
	public void delete(EmpSerReqHistoryPk pk) throws EmpSerReqHistoryDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL_DELETE + " with PK: " + pk);
			}
		
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			if (logger.isDebugEnabled()) {
				logger.debug( rows + " rows affected (" + (t2-t1) + " ms)");
			}
		
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new EmpSerReqHistoryDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the EMP_SER_REQ_HISTORY table that matches the specified primary-key value.
	 */
	public EmpSerReqHistory findByPrimaryKey(EmpSerReqHistoryPk pk) throws EmpSerReqHistoryDaoException
	{
		return findByPrimaryKey( pk.getId() );
	}

	/** 
	 * Returns all rows from the EMP_SER_REQ_HISTORY table that match the criteria 'ID = :id'.
	 */
	public EmpSerReqHistory findByPrimaryKey(int id) throws EmpSerReqHistoryDaoException
	{
		EmpSerReqHistory ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID = ?", new Object[] {  new Integer(id) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the EMP_SER_REQ_HISTORY table that match the criteria ''.
	 */
	public EmpSerReqHistory[] findAll() throws EmpSerReqHistoryDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID", null );
	}

	/** 
	 * Returns all rows from the EMP_SER_REQ_HISTORY table that match the criteria 'ID = :id'.
	 */
	public EmpSerReqHistory[] findWhereIdEquals(long id) throws EmpSerReqHistoryDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID = ? ORDER BY ID", new Object[] {  new Long(id) } );
	}

	/** 
	 * Returns all rows from the EMP_SER_REQ_HISTORY table that match the criteria 'ESR_MAP_ID = :esrMapId'.
	 */
	public EmpSerReqHistory[] findWhereEsrMapIdEquals(int esrMapId) throws EmpSerReqHistoryDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ESR_MAP_ID = ? ORDER BY ESR_MAP_ID", new Object[] {  new Integer(esrMapId) } );
	}

	/** 
	 * Returns all rows from the EMP_SER_REQ_HISTORY table that match the criteria 'ACTION_ON = :actionOn'.
	 */
	public EmpSerReqHistory[] findWhereActionOnEquals(Date actionOn) throws EmpSerReqHistoryDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ACTION_ON = ? ORDER BY ACTION_ON", new Object[] { actionOn==null ? null : new java.sql.Timestamp( actionOn.getTime() ) } );
	}

	/** 
	 * Returns all rows from the EMP_SER_REQ_HISTORY table that match the criteria 'ASSIGNED_TO = :assignedTo'.
	 */
	public EmpSerReqHistory[] findWhereAssignedToEquals(int assignedTo) throws EmpSerReqHistoryDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ASSIGNED_TO = ? ORDER BY ASSIGNED_TO", new Object[] {  new Integer(assignedTo) } );
	}

	/** 
	 * Returns all rows from the EMP_SER_REQ_HISTORY table that match the criteria 'ASSIGNED_BY = :assignedBy'.
	 */
	public EmpSerReqHistory[] findWhereAssignedByEquals(int assignedBy) throws EmpSerReqHistoryDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ASSIGNED_BY = ? ORDER BY ASSIGNED_BY", new Object[] {  new Integer(assignedBy) } );
	}

	/** 
	 * Returns all rows from the EMP_SER_REQ_HISTORY table that match the criteria 'COMMENTS = :comments'.
	 */
	public EmpSerReqHistory[] findWhereCommentsEquals(String comments) throws EmpSerReqHistoryDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE COMMENTS = ? ORDER BY COMMENTS", new Object[] { comments } );
	}

	/**
	 * Method 'EmpSerReqHistoryDaoImpl'
	 * 
	 */
	public EmpSerReqHistoryDaoImpl()
	{
	}

	/**
	 * Method 'EmpSerReqHistoryDaoImpl'
	 * 
	 * @param userConn
	 */
	public EmpSerReqHistoryDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "EMP_SER_REQ_HISTORY";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected EmpSerReqHistory fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			EmpSerReqHistory dto = new EmpSerReqHistory();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected EmpSerReqHistory[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection<EmpSerReqHistory> resultList = new ArrayList<EmpSerReqHistory>();
		while (rs.next()) {
			EmpSerReqHistory dto = new EmpSerReqHistory();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		EmpSerReqHistory ret[] = new EmpSerReqHistory[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(EmpSerReqHistory dto, ResultSet rs) throws SQLException
	{
		dto.setId( rs.getInt( COLUMN_ID ) );
		dto.setEsrMapId( rs.getInt( COLUMN_ESR_MAP_ID ) );
		dto.setActionOn( rs.getTimestamp(COLUMN_ACTION_ON ) );
		dto.setAssignedTo( rs.getInt( COLUMN_ASSIGNED_TO ) );
		dto.setAssignedBy( rs.getInt( COLUMN_ASSIGNED_BY ) );
		dto.setComments( rs.getString( COLUMN_COMMENTS ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(EmpSerReqHistory dto)
	{
	}

	/** 
	 * Returns all rows from the EMP_SER_REQ_HISTORY table that match the specified arbitrary SQL statement
	 */
	public EmpSerReqHistory[] findByDynamicSelect(String sql, Object[] sqlParams) throws EmpSerReqHistoryDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new EmpSerReqHistoryDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the EMP_SER_REQ_HISTORY table that match the specified arbitrary SQL statement
	 */
	public EmpSerReqHistory[] findByDynamicWhere(String sql, Object[] sqlParams) throws EmpSerReqHistoryDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			if (logger.isDebugEnabled()) {
				logger.debug( "Executing " + SQL);
			}
		
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			logger.error( "Exception: " + _e.getMessage(), _e );
			throw new EmpSerReqHistoryDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	@Override
	public EmpSerReqHistory findWhereEsrMapIdEqualsMax(int esrMapId) throws EmpSerReqHistoryDaoException {
		EmpSerReqHistory[] esrqh =	findByDynamicWhere("ID=(SELECT MAX(ID) FROM EMP_SER_REQ_HISTORY WHERE ESR_MAP_ID=?)", new Object[]{esrMapId});
		return esrqh==null?null:esrqh.length>0?esrqh[0]:null;
	}

}
