package com.dikshatech.portal.actions;

import java.sql.SQLException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.fileupload.FileItem;

import com.dikshatech.portal.exceptions.FbpDetailsDaoException;
import com.dikshatech.portal.exceptions.FbpReqDaoException;
//import com.dikshatech.portal.exceptions.NDAOnlineExamReportDaoException;
import com.dikshatech.portal.exceptions.RetentionBonusReconciliationReportDaoException;
import com.dikshatech.portal.exceptions.SalaryDetailsDaoException;
import com.dikshatech.portal.exceptions.VoluntaryProvidentFundDaoException;
import com.dikshatech.portal.forms.PortalForm;
import com.dikshatech.portal.mail.Attachements;

public abstract class ActionMethods {

	protected enum ValidationTypes {
		USEREXISTS, IsValidSession, UNKNOWN, ISVALIDFOREDIT;

		public static ValidationTypes getValue(String value) {
			try{
				return valueOf(value);
			} catch (Exception e){
				return UNKNOWN;
			}
		};
	}

	public enum ReceiveTypes {
		UPDATERECEIVE,RECEIVEUSER, RECEIVEALLUSER, PDF_CONVERTION, EMAIL_PDF, RECEIVEREGION, RECEIVEALLREGION, RECEIVESUBSKILLS, RECEIVEDIVISION, RECEIVEALLDIVISION, 
		UNKNOWN, RECEIVEALLCOMPANY, RECEIVECOMPANY, RECEIVEALLLEVELS, RECEIVELEVEL, RECEIVE, RECEIVEALLCANDIDATE, RECEIVEALL, RECEIVEDOCKED, 
		RECEIVEPERIOD, RECEIVEALLMODULES, RECEIVEALLROLES, RECEIVEROLES, RECEIVETIMESHEET, RECEIVEALLTIMESHEET, MANAGETIMESHEET, ALLMODULESFEATURES,
		RECEIVECOMPANYRECORD, RECEIVEALLDEPARTMENTBYREGION, RECEIVEALLLEVELSBYDIVISION, RECEIVEHOLIDAYLIST, RECEIVEUPDATEPROFILE, 
		RECEIVEEDITEMPLOYEE, RECEIVEALLUSERTAT, RECEIVEUSERSBYLEVEL, RECEIVEDESIGNATION, RECEIVEUSERSBYDEPARTMENT, RECEIVEUSERSBYDIVISION, 
		RECEIVEUSERSBYREGIONS, RECEIVEUSERSBYCOMPANY, RECEIVEPROCESSCHAIN, RECEIVEALLPROCESSCHAIN, RECEIVEACCESSIBILITY, OFFERPREVIEW, RECEIVEBYCALID, 
		RECEIVESEPERATEDLIST, GETDETAILS, RECEIVEALLCLIENT, RECEIVECLIENT, RECEIVEALLPERDIEM, RECEIVEALLPROJECT, RECEIVEPROJECTSOFCLIENT, 
		RECEIVEPROJECT, EMPINPROJECT, EMPONBENCH, RECEIVETASK, RECEIVETASKSBYPROJECT, RECEIVEALLTASKS, RECEIVEPROJECTBYCOMPANY, RECEIVEPROJECTBYREGION, 
		RECEIVEPROJECTBYDEPT, LEAVERECEIVE, LEAVEFORAPPROVE, LEAVESINGLERECEIVE, LEAVETYPES, LEAVEACCUMALATOR, RECEIVEPROJECTBYDIVISION, ALLTASKLIST, 
		TSHEETFORAPPROVE, RECEIVEALLLEVELSBYREGION, RECEIVENEW, RECEIVESINGLEROLLON, MYROLLONRESOURCE, RECEIVEALLCONSULTANT, RECEIVEUSERRESOURCE, 
		RECEIVEALLLOAN, RECEIVELOAN, NEWLOANRECEIVE, RECEIVEALLTYPES, RECEIVELOANHANDLERS, HRSPOCS, SEPARATEDUSERS, RECEIVECOMPANYRESOURCE, 
		RECEIVEREGIONRESOURCE, RECEIVEPODETAILS, RECEIVEPROJFORPODETAILS, RECEIVEUSERVIEW, HANDLER, RECEIVEBIRTHDAYS, RECEIVECATEGORY, ITSUPPORT, 
		RECEIVETOAPPROVE, RECEIVEALLTOAPPROVE, RECEIVEALLTOHANDLE, RECEIVECURRENCY, RECEIVETYPE, RECEIVEALLSTATUS, RECEIVETOHANDLE, RECEIVEBUTTONINFO, 
		RECEIVEISSUES, RECEIVEALLISSUES, ISSUESWITHDEPT, ISSUESTOAPPROVE, ISSUESTOHANDLE, HANDLERSINGLEISSUERECEIVE, HANDLERSLIST, DEPENDENTLIST, 
		EMPLOYEESERREQINFO, RECEIVEMYTASKS, RECEIVEPROJECTOWNER, MYRESOURCES, MYPROJECTS, RECEIVEPROJECTBYEMPLOYEE, RECEIVEPROJECTSOWNED, 
		RECEIVEALLPROJECTSFORHR, RECEIVESIBLINGS, RECEIVEREQHISTORY, RECEIVEUSERS, APPRAISALREPORTS, APPRAISALHRREPORTS, RECEIVEUSERSBYAPPRAISER, 
		EMPLOYEETYPE, RECEIVESINGLEPROFILE, RESUMESEARCHRECEIVE, RECEIVEINFO, RECEIVEQUESTIONS, RECEIVEALLFORHR, RECEIVEANSWERS, RECEIVEDETAILS, 
		RECEIVEALLNOC, RECEIVENOC, RMRESOURCE, HRSPOCRESOURCE, RECEIVERMS, RECEIVEHRSPOCS, ESCALATION, ESCALATIONUSERS, RECEIVEALLUSERSBYLEVELS, 
		RECEIVEESCALATIONUSERS,RECEIVEDECLARATION,RECEIVEQUESTIONNARIE,RECEIVECLOSURE, RECEIVEPERDIEM, RECEIVEALLPERDIEMS,
		CALCULATEDSALARY, // Added rType for the Salary restructure
		RECEIVEEMPLOYEESFORPERDIEM, RECEIVEMASTER, RECEIVECONFIG, RECEIVETAXBENEFIT, RECEIVETDS, RECEIVEREPORT, RECEIVECALCULATION, 
         RECEIVEESCALATIONS, RECEIVECANDIDATECHECKLIST, CURRENCYRATES, TOAPPROVE, TOHANDLE, BANKACCOUNTS, RECEIVEEMPLOYEESFORBONUS, RECEIVEALLREPORTINGMGR, OFFERFORAPPROVAL, RECEIVECALENDAR,
         RECEIVEHOLIDAYLIST_TIMESHEET, RECIEVEALLREQUIREMENTS, RECEIVEALLANDROIDUSER, GLOBALPROJECT, RECEIVEALLRESOURCESTATUS, RECEIVEALLTATASSIGNEES,RECEIVE_ALL_EMPLOYMENT_TYPES,
         RECEIVE_ALL_MAIN_STATUS, RECEIVEPROPOSEDCANDIDATES, RECEIVESINGLECANDIDATES, RECEIVEALLRESOURCES, RECEIVEALLREQUESTIDS, RECEIVEALLSELECTEDRESOURCES,
         RECEIVECANDIDATE,RECEIVEPAY,RECEIVEALLPAIDANDUNPAID,RECEIVEALLACTIVECHARGECODE,RECEIVEPODETAILSFORCHARGECODE,UPDATEPODETAILFORCHARGECODE,RECEIVERMGTIMESHEET,RECEIVEUPDATEDREPORT,RECEIVEALLLOCATIONS,RECEIVETDSI,RECEIVEIMAGENAME,RECEIVEALLCATEGORY, RECEIVEALL_FBP_STATUS,RECEIVEALL_ESIC_STATUS;


		public static ReceiveTypes getValue(String value) {
			try{
				return valueOf(value);
			} catch (Exception e){
				return UNKNOWN;
			}
		};
	};

	public enum DownloadTypes {
		GENERATEOFFER, UNKNOWN, APPRAISALHRDREPORTS, APPRAISALHRREPORTS, LEAVEBALANCESHEET, SODEXOREPORT, REIMBURSEMENTLIST, DELAYEDTIMESHEETLIST,FBPDECLARATION, 
 BANKLETTER, SALARYDISBURSEMENT, PERDIEMREPORT, TIMESHEETREPORT, ICICIREPORT, OTHERREPORT, BONUSREPORT ,RESOURCERESUME,RETENTIONBONUSREPORT,DOCSUSER,ALLEMPDETAILS,INVOICEREPORT,FINALREPORT,REIMBURSEMENTLISTD;//ONLINEEXAMREPORT

		public static DownloadTypes getValue(String value) {
			try{
				return valueOf(value);
			} catch (Exception e){
				return UNKNOWN;
			}
		};
	};

	protected enum ExecuteTypes {
		LOGIN, LOGOUT, UNKNOWN, DISABLECLIENT, ENABLECLIENT, ADDUSERTOPROJECT, REMOVEUSERFROMPROJECT, ADDCHARGECODETOPROJECT,
		DISABLEPROJECT, ROLLOFF, ENABLEPROJECT, ADDTASKS, UPLOAD, DOWNLOAD, ENABLEPODETAIL, DISABLEPODETAIL, CHANGEPASSWORD, BIRTHDAY, 
		UPDATERM, UPDATEHRSPOC, ADDAPPRAISERS, UPDATEAPPRAISERS, REMOVEAPPRAISERS, RESUMESKILLSET, USSTATES, SENDAPPRAISALMAIL,UPDATE;

		public static ExecuteTypes getValue(String value) {
			try{
				return valueOf(value);
			} catch (Exception e){
				return UNKNOWN;
			}
		};
	};

	protected enum SubTypes {
		UNKNOWN, DIVISION, SUBDIVISION;

		public static SubTypes getValue(String value) {
			try{
				return valueOf(value);
			} catch (Exception e){
				return UNKNOWN;
			}
		};
	};

	public enum DeleteTypes {
		UNKNOWN, DELETEALL, FORCEFULLYMULTIDELETE, DELETE, DELETEFEW,DELETEMANY;

		public static DeleteTypes getValue(String value) {
			try{
				return valueOf(value);
			} catch (Exception e){
				return UNKNOWN;
			}
		};
	};

	public enum SaveTypes {
		UNKNOWN, SAVE, DEFAULT_INSURANCE, CANCELLSAVE, SUBMIT, MARKCANDIDATEASEMPLOYEE, SAVEANDSUBMIT, ASSIGN, REASSIGN, RESOLVED, CLOSED, 
		CLOSEDBYREQUESTOR, CANCELLED, SINGLEROLLON, MULTIPLEROLLON, INPROGRESS, REVOKED, REOPEN, FINANCENOC, ITNOC, ADMINNOC, SUBMITNOC, WITHDRAW,
 REJECTED, SUBMITDECLARATION, SUBMITQUESTIONNARIE, SUBMITCLOSURE, SAVEPERDIEM, SAVEMASTER, SAVETDS, ADD, DELETE, CURRENCYRATES, HOLD, RELEASE, BANKACCOUNTS, CHANGEREPORTINGMGR, GETANDROID,  SENDMESSAGEFORSELECTEDANDROIDUSERS, DELETEREGID, SAVECANDIDATE ,SAVEVPF,SAVECORDOVA;

		public static SaveTypes getValue(String value) {
			try{
				return valueOf(value);
			} catch (Exception e){
				return UNKNOWN;
			}
		};
	};

	public enum UpdateTypes {
		UPDATE, UPDATEID, UPDATEREGION, UNKNOWN, ENABLEDISABLE, UPDATECANDIDATE, UPDATEFOREMPLOYEE, SENDOFFERLETTER, UPLOAD, ACCEPTREJECTOFFER, 
		RESENDOFFERLETTER, UPDATECANDIDATEREQ, GENERATEOFFER, FORGOTPASSWORD, GENERATEEMPLOYEEID, VALIDATEEMPLOYEEID, LEAVEAPPROVE, ATELEAVE, 
		LEAVERECEIVE, MARKREAD, EDIT, UPDATETRAVEL, NOSHOW, ACCEPTED, REJECTED, HOLD, APPROVEREJECTCANCELL, LEAVECANCELED, LEAVEREJECT, CANCELED, ASSIGN,
		ACCEPTREJECT, CANCEL, SUBMIT, APPROVE, CANCELREQUEST, CANCELACTION, INPROGRESS, RESOLVED, CLOSEDBYREQUESTOR, APPROVERASSIGN, INSURANCEAPPROVE, 
 INSURANCEREJECT, INSURANCEONHOLD, INSURANCEASSIGN, INSURANCESIBLINGSLIST, UPDATEINSURANCE, UPDATEPERDIEM, PROCESSSED, UPDATEBYHANDLER, CHANGEPASSWORD, RECEIVE_LOGIN, UPDATECANDIDATECHKLST, MARKASINCOMPLETE, MARKASCOMPLETE, BANKACCOUNTS, PROCEED, CLOSED,UPDATEDOCUMENT ,UPDATERESOURCE, NONPAYMENT;

		public static UpdateTypes getValue(String value) {
			try{
				return valueOf(value);
			} catch (Exception e){
				return UNKNOWN;
			}
		};
	};

	public enum CategoryTypes {
		SODEXO, ISSUES, ITSUPPORT, TRAVEL, UNKNOWN, CANDIDATE, REIMBURSEMENT, INSURANCE;

		public static CategoryTypes getValue(String value) {
			try{
				return valueOf(value);
			} catch (Exception e){
				return UNKNOWN;
			}
		};
	};

	public abstract ActionResult login(PortalForm form, HttpServletRequest request) throws SQLException;

	public abstract ActionResult save(PortalForm form, HttpServletRequest request) throws RetentionBonusReconciliationReportDaoException, VoluntaryProvidentFundDaoException; //NDAOnlineExamReportDaoException;

	public abstract ActionResult receive(PortalForm form, HttpServletRequest request) throws VoluntaryProvidentFundDaoException;

	public abstract ActionResult update(PortalForm form, HttpServletRequest request);

	public abstract ActionResult delete(PortalForm form, HttpServletRequest request);

	public abstract ActionResult validate(PortalForm form, HttpServletRequest request);

	public abstract ActionResult exec(PortalForm form, HttpServletRequest request) throws  VoluntaryProvidentFundDaoException, FbpReqDaoException, SalaryDetailsDaoException, FbpDetailsDaoException;

	public abstract ActionResult defaultMethod(PortalForm form, HttpServletRequest request, HttpServletResponse response);

	public Integer[] upload(List<FileItem> fileItems, String docType, int id, HttpServletRequest request, String description) {
		
		return null;	// TODO Auto-generated method stub
	}

	public Attachements download(PortalForm form) {
		return null;
	}

	public ActionResult deleteFiles(PortalForm form) {
		return null;
	}

	public List<Integer> getNextProcId(String procChain, int esrMapId) {
		return null;
	}

	
}