/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.dikshatech.portal.factory;

import java.sql.Connection;

import com.dikshatech.portal.dao.CandidatePerdiemDetailsDao;
import com.dikshatech.portal.jdbc.CandidatePerdiemDetailsDaoImpl;

public class CandidatePerdiemDetailsDaoFactory {
	/**
	 * Method 'create'
	 * 
	 * @return CandidatePerdiemDetailsDao
	 */
	public static CandidatePerdiemDetailsDao create() {
		return new CandidatePerdiemDetailsDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return CandidatePerdiemDetailsDao
	 */
	public static CandidatePerdiemDetailsDao create(Connection conn) {
		return new CandidatePerdiemDetailsDaoImpl(conn);
	}

}
