/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package com.dikshatech.portal.dao;

import com.dikshatech.portal.dto.DepPerdiemComponents;
import com.dikshatech.portal.dto.DepPerdiemComponentsPk;
import com.dikshatech.portal.exceptions.DepPerdiemComponentsDaoException;

public interface DepPerdiemComponentsDao {

	/** 
	 * Inserts a new row in the DEP_PERDIEM_COMPONENTS table.
	 */
	public DepPerdiemComponentsPk insert(DepPerdiemComponents dto) throws DepPerdiemComponentsDaoException;

	/** 
	 * Updates a single row in the DEP_PERDIEM_COMPONENTS table.
	 */
	public void update(DepPerdiemComponentsPk pk, DepPerdiemComponents dto) throws DepPerdiemComponentsDaoException;

	/** 
	 * Deletes a single row in the DEP_PERDIEM_COMPONENTS table.
	 */
	public void delete(DepPerdiemComponentsPk pk) throws DepPerdiemComponentsDaoException;

	/** 
	 * Returns the rows from the DEP_PERDIEM_COMPONENTS table that matches the specified primary-key value.
	 */
	public DepPerdiemComponents findByPrimaryKey(DepPerdiemComponentsPk pk) throws DepPerdiemComponentsDaoException;

	/** 
	 * Returns all rows from the DEP_PERDIEM_COMPONENTS table that match the criteria 'ID = :id'.
	 */
	public DepPerdiemComponents findByPrimaryKey(Integer id) throws DepPerdiemComponentsDaoException;

	/** 
	 * Returns all rows from the DEP_PERDIEM_COMPONENTS table that match the criteria 'REP_ID = :repId'.
	 */
	public DepPerdiemComponents[] findWhereRepIdEquals(Integer repId) throws DepPerdiemComponentsDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the DEP_PERDIEM_COMPONENTS table that match the specified arbitrary SQL statement
	 */
	public DepPerdiemComponents[] findByDynamicSelect(String sql, Object[] sqlParams) throws DepPerdiemComponentsDaoException;

	/** 
	 * Returns all rows from the DEP_PERDIEM_COMPONENTS table that match the specified arbitrary SQL statement
	 */
	public DepPerdiemComponents[] findByDynamicWhere(String sql, Object[] sqlParams) throws DepPerdiemComponentsDaoException;
}
