/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.dikshatech.portal.dao;

import com.dikshatech.portal.dto.*;
import com.dikshatech.portal.exceptions.*;

public interface EmployeeTypeDao
{
	/** 
	 * Inserts a new row in the EMPLOYEE_TYPE table.
	 */
	public EmployeeTypePk insert(EmployeeType dto) throws EmployeeTypeDaoException;

	/** 
	 * Updates a single row in the EMPLOYEE_TYPE table.
	 */
	public void update(EmployeeTypePk pk, EmployeeType dto) throws EmployeeTypeDaoException;

	/** 
	 * Deletes a single row in the EMPLOYEE_TYPE table.
	 */
	public void delete(EmployeeTypePk pk) throws EmployeeTypeDaoException;

	/** 
	 * Returns the rows from the EMPLOYEE_TYPE table that matches the specified primary-key value.
	 */
	public EmployeeType findByPrimaryKey(EmployeeTypePk pk) throws EmployeeTypeDaoException;

	/** 
	 * Returns all rows from the EMPLOYEE_TYPE table that match the criteria 'ID = :id'.
	 */
	public EmployeeType findByPrimaryKey(int id) throws EmployeeTypeDaoException;

	/** 
	 * Returns all rows from the EMPLOYEE_TYPE table that match the criteria ''.
	 */
	public EmployeeType[] findAll() throws EmployeeTypeDaoException;

	/** 
	 * Returns all rows from the EMPLOYEE_TYPE table that match the criteria 'ID = :id'.
	 */
	public EmployeeType[] findWhereIdEquals(int id) throws EmployeeTypeDaoException;

	/** 
	 * Returns all rows from the EMPLOYEE_TYPE table that match the criteria 'EMPLOYEE_TYPE = :employeeType'.
	 */
	public EmployeeType[] findWhereEmployeeTypeEquals(String employeeType) throws EmployeeTypeDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the EMPLOYEE_TYPE table that match the specified arbitrary SQL statement
	 */
	public EmployeeType[] findByDynamicSelect(String sql, Object[] sqlParams) throws EmployeeTypeDaoException;

	/** 
	 * Returns all rows from the EMPLOYEE_TYPE table that match the specified arbitrary SQL statement
	 */
	public EmployeeType[] findByDynamicWhere(String sql, Object[] sqlParams) throws EmployeeTypeDaoException;

}
