/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.dikshatech.portal.dao;

import java.util.Date;
import com.dikshatech.portal.dto.*;
import com.dikshatech.portal.exceptions.*;

public interface PerdiemInAdvanceDao
{
	/** 
	 * Inserts a new row in the PERDIEM_IN_ADVANCE table.
	 */
	public PerdiemInAdvancePk insert(PerdiemInAdvance dto) throws PerdiemInAdvanceDaoException;

	/** 
	 * Updates a single row in the PERDIEM_IN_ADVANCE table.
	 */
	public void update(PerdiemInAdvancePk pk, PerdiemInAdvance dto) throws PerdiemInAdvanceDaoException;

	/** 
	 * Deletes a single row in the PERDIEM_IN_ADVANCE table.
	 */
	public void delete(PerdiemInAdvancePk pk) throws PerdiemInAdvanceDaoException;

	/** 
	 * Returns the rows from the PERDIEM_IN_ADVANCE table that matches the specified primary-key value.
	 */
	public PerdiemInAdvance findByPrimaryKey(PerdiemInAdvancePk pk) throws PerdiemInAdvanceDaoException;

	/** 
	 * Returns all rows from the PERDIEM_IN_ADVANCE table that match the criteria 'ID = :id'.
	 */
	public PerdiemInAdvance findByPrimaryKey(Integer id) throws PerdiemInAdvanceDaoException;

	/** 
	 * Returns all rows from the PERDIEM_IN_ADVANCE table that match the criteria ''.
	 */
	public PerdiemInAdvance[] findAll() throws PerdiemInAdvanceDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the PERDIEM_IN_ADVANCE table that match the specified arbitrary SQL statement
	 */
	public PerdiemInAdvance[] findByDynamicSelect(String sql, Object[] sqlParams) throws PerdiemInAdvanceDaoException;

	/** 
	 * Returns all rows from the PERDIEM_IN_ADVANCE table that match the specified arbitrary SQL statement
	 */
	public PerdiemInAdvance[] findByDynamicWhere(String sql, Object[] sqlParams) throws PerdiemInAdvanceDaoException;

}
